version: "3.8"
services:
  backend:
    build:
      context: .
    ports:
      - "9000:9000"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
  frontend:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
volumes:
  logs:
