version: "3.8"

services:
  nginx:
    image: faisal7008/worktrackr-app:nginx-latest
    restart: always
    depends_on:
      - client
      - server
    ports:
      - "80:80"

  client:
    image: faisal7008/worktrackr-app:frontend-latest
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}

  server:
    image: faisal7008/worktrackr-app:backend-latest
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_URI=${MONGO_URI}
