version: "3.8"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    restart: always
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    env_file:
      - ./frontend/.env
    restart: always
    depends_on:
      - backend
