# The name of the workflow.
name: Build and Deploy

# Run the workflow when code is pushed to the deploy branch
on:
  push:
    branches:
      - deploy

# Set environment variables
env:
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  MONGO_URI: ${{ secrets.MONGO_URI }}
  REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}

# This is the workflow that is being run.
jobs:
  build-and-deploy:
    # This is telling GitHub to run the workflow on the latest version of Ubuntu.
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the GitHub repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies and run tests for the frontend application
      - name: Install and Test Client
        working-directory: ./frontend
        run: |
          npm install
          REACT_APP_API_URL=$REACT_APP_API_URL
          npm run test

      # Install dependencies, export environment variables to be used by application and run tests for the backend application
      - name: Install and Test Server
        working-directory: ./backend
        run: |
          npm install
          export JWT_SECRET=$JWT_SECRET
          export MONGO_URI=$MONGO_URI
          npm run test

      # Build a Docker image for the frontend application
      - name: Build Client Docker Image
        working-directory: ./frontend
        # Build image with tag faisal7008/worktrackr-app:frontend
        run: |
          docker build -t faisal7008/worktrackr-app:frontend-${{github.run_number}} -t faisal7008/worktrackr-app:frontend-latest .

      # Build a Docker image for the backend application
      - name: Build Server Docker Image
        working-directory:
          ./backend
          # Build image with tag faisal7008/worktrackr-app:backend
        run: |
          docker build -t faisal7008/worktrackr-app:backend-${{github.run_number}} -t faisal7008/worktrackr-app:backend-latest .

      # Build a Docker image for the NGINX reverse proxy
      - name: Build NGINX Docker Image
        working-directory: ./nginx
        # Build image with tag faisal7008/worktrackr-app:nginx
        run: |
          docker build -t faisal7008/worktrackr-app:nginx-${{github.run_number}} -t faisal7008/worktrackr-app:nginx-latest .

      # Log in to Docker Hub using credentials from repository secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push the Docker images to Docker Hub
      - name: Push Docker Images to Docker Hub
        run: |
          docker push faisal7008/worktrackr-app:frontend-${{github.run_number}}
          docker push faisal7008/worktrackr-app:backend-${{github.run_number}}
          docker push faisal7008/worktrackr-app:nginx-${{github.run_number}}
          docker push faisal7008/worktrackr-app:frontend-latest
          docker push faisal7008/worktrackr-app:backend-latest
          docker push faisal7008/worktrackr-app:nginx-latest

      # This is the step that is deploying the application to Elastic Beanstalk.
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.EB_APP_NAME }}
          environment_name: ${{ secrets.EB_ENV_NAME }}
          region: ${{ secrets.EB_REGION }}
          version_label: "version-${{ github.run_number }}"
          deployment_package: docker-compose.yml
